### ISSUE TITLE
Getting a 404 on an npm install for har-validator-5.1.2.tgz

### ISSUE THREAD

**Issue by Mrandles89** [ahmadnassri/node-har-validator#113] opened 2018-11-12 17:32 UTC
When I run an npm install, I am now getting a 404 on the har-validator-5.1.2.tgz package. This just started occurring over the weekend.

15420 error code E404
15421 error 404 Not Found: har-validator@https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz

NPM version: 5.6.0
Node version: 8.9.4

**Comment by kevincolten** [comment] 2018-11-12 18:06
@ahmadnassri There is a version mismatch for this package and the npm/yarn repos. The current version is 5.1.2 and it is published under 5.1.3

**Comment by nullpointer77** [comment] 2018-11-12 20:57
@kevincolten I hear you, but there are many old versions of various npm libs that are specifically looking for 5.1.2.  protactor being one of them.  I don't see a way to redirect specific npm packages that I don't control.  Would you be able to push whatever the latest is out as 5.1.2 out to the npm repo?

**Comment by bdunn313** [comment] 2018-11-13 00:12
Anyone have a solution for this?

**Comment by danoc** [comment] 2018-11-13 00:41
Was able to work around this by bumping up the version of the package I had that depended on `har-validator`.

If using Yarn, you can figure this out by running `yarn why har-validator`.

**Comment by cdimascio** [comment] 2018-11-13 02:25
I was able to fix one of two projects by uninstalling and reinstalling the package with the dependency on har-validator.

For the second project i replaced, the har-validator entry in `package-lock.json` with this

```json
    "har-validator": {
      "version": "5.1.3",
      "resolved": "https://registry.npmjs.org/har-validator/-/har-validator-5.1.3.tgz",
      "integrity": "sha512-sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==",
      "requires": {
        "ajv": "^6.5.5",
        "har-schema": "^2.0.0"
      }
    }
```

hope this helps

**Comment by bambielli** [comment] 2018-11-13 03:03
Installing har-validator 5.1.3 in my project solved the issue for me.
Hope this is fixed soon, though.

**Comment by nullpointer77** [comment] 2018-11-13 08:07
@cdimascio is my hero for the day.  This corrected my problem.

**Comment by Kmaschta** [comment] 2018-11-13 10:11
Does someone have contacted NPM about that issue?

**Comment by guanxf** [comment] 2018-11-13 10:47
update the package (like request 2.88.0 dependency of har-validator ~5.1.0)

**Comment by hodgef** [comment] 2018-11-14 14:40
This issue seems to be causing my Travis CI tests to fail. Reached out to npm support about it
![error](https://user-images.githubusercontent.com/25509135/48489546-51c80e00-e7f1-11e8-93e0-32a81c5f8a05.PNG)

**Comment by CS-Tao** [comment] 2018-11-15 01:20
Delete `yarn.lock` or `package-lock.json` and install dependencies again fixed my problem. A new patch version v5.1.3 was linked in my new lock file.

**Comment by pgonzal** [comment] 2018-11-15 22:20
> There is a version mismatch for this package and the npm/yarn repos. The current version is 5.1.2 and it is published under 5.1.3

@kevincolten how did this problem occur?  The behavior seems as if someone ran `npm unpublish har-validator@5.1.2` after the package was originally published.  (?)

**Comment by rubensa** [comment] 2018-11-16 12:57
> > There is a version mismatch for this package and the npm/yarn repos. The current version is 5.1.2 and it is published under 5.1.3
> 
> @kevincolten how did this problem occur? The behavior seems as if someone ran `npm unpublish har-validator@5.1.2` after the package was originally published. (?)

Unpublish confirmation:
https://github.com/ahmadnassri/node-har-validator/issues/112#issuecomment-437378269

**Comment by ahmadnassri** [comment] 2018-11-16 18:02
closing this to continue the discussion in #112

**Closed by ahmadnassri** 2018-11-16 18:02 UTC

**Comment by Steffi3rd** [comment] 2018-11-29 09:35
> I was able to fix one of two projects by uninstalling and reinstalling the package with the dependency on har-validator.
> 
> For some reason, this didn't help with my second project. To resolve that one, I replaced the har-validator entry in `package-lock.json` with this:
> 
> ```json
>     "har-validator": {
>       "version": "5.1.3",
>       "resolved": "https://registry.npmjs.org/har-validator/-/har-validator-5.1.3.tgz",
>       "integrity": "sha512-sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==",
>       "requires": {
>         "ajv": "^6.5.5",
>         "har-schema": "^2.0.0"
>       }
>     }
> ```
> 
> That resolved my second project.
> 
> hope this helps

That worked for me. Don't know why... ^^  Thanks

**Comment by jxc876** [comment] 2018-12-06 22:38
this broke several apps for us today, the fix was to change the version in the package-lock.json file.

**Comment by devpascoe** [comment] 2018-12-07 02:49
for me latest node-sass was using this package. Rolled back to a previous version and all good
"node-sass": "~4.9.4",

**Comment by felixcatto** [comment] 2018-12-13 14:51
I removed  package-lock.json, execute "npm i". Then cleared cache on heroku https://coderwall.com/p/jjcpra/clean-heroku-npm-cache
then i finally was able to push my changes on heroku without errors.

**Comment by damuz91** [comment] 2018-12-16 22:07
I can confirm that deleting package-lock.json AND installing latest with $npm install har-validator@latest --save-dev did fix the issue

**Comment by mehsan1** [comment] 2019-01-03 12:14
All you need to do is delete "package-lock.json" and run command "npm install"

**Comment by blessochampion** [comment] 2019-01-11 15:53
`Yarn install` fixed this for me.

**Comment by taufik1207** [comment] 2019-05-13 04:09
> I was able to fix one of two projects by uninstalling and reinstalling the package with the dependency on har-validator.
> 
> For some reason, this didn't help with my second project. To resolve that one, I replaced the har-validator entry in `package-lock.json` with this:
> 
> ```json
>     "har-validator": {
>       "version": "5.1.3",
>       "resolved": "https://registry.npmjs.org/har-validator/-/har-validator-5.1.3.tgz",
>       "integrity": "sha512-sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==",
>       "requires": {
>         "ajv": "^6.5.5",
>         "har-schema": "^2.0.0"
>       }
>     }
> ```
> 
> That resolved my second project.
> 
> hope this helps

Thanks u, you my hero..
